# Generated by Django 4.1 on 2024-02-29 12:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSubscriber',
            fields=[
            ],
            options={
                'verbose_name': 'Blog Subscriber',
                'verbose_name_plural': 'Blog Subscribers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ShopSubscriber',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Subscriber',
                'verbose_name_plural': 'Shop Subscribers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
